export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://beaconvie.com";

export type SeoPage = {
  slug: string; title: string; description: string; eyebrow: string; heading: string; intro: string;
  outcomes: string[]; appPath: string;
  lesson: { title: string; explanation: string; examples: string[]; practice: string; answer: string };
  guide?: string[];
  faqs?: { q: string; a: string }[];
};

export const seoPages: SeoPage[] = [
  { slug:"hoc-tieng-anh", title:"Học tiếng Anh online theo lộ trình cá nhân hóa", description:"Học tiếng Anh online cùng BeaconVie với lộ trình theo CEFR, luyện đủ 6 kỹ năng và theo dõi tiến bộ mỗi ngày.", eyebrow:"Lộ trình học tiếng Anh", heading:"Học tiếng Anh có lộ trình, không học lan man", intro:"Bắt đầu từ trình độ hiện tại, luyện đúng kỹ năng còn yếu và duy trì nhịp học mỗi ngày.", outcomes:["Xác định trình độ CEFR","Lộ trình học theo mục tiêu","Luyện đủ nghe, nói, đọc, viết, từ vựng và ngữ pháp"], appPath:"/learning-path", lesson:{title:"Mini lesson: một nhịp học 15 phút",explanation:"5 phút ôn từ vựng, 5 phút nghe hoặc đọc và 5 phút tự tạo một câu mới. Nhịp ngắn giúp bạn duy trì việc học đều thay vì dồn nhiều giờ vào một ngày.",examples:["Word: routine — thói quen","Read: I study English every evening.","Create: I practise listening after dinner."],practice:"Hãy tự nói hoặc viết một câu về thói quen học tiếng Anh của bạn.",answer:"Gợi ý: I practise English for fifteen minutes every evening."}},
  { slug:"kiem-tra-trinh-do-tieng-anh", title:"Kiểm tra trình độ tiếng Anh theo CEFR", description:"Kiểm tra trình độ tiếng Anh và xác định mức CEFR từ A1 đến C1 để bắt đầu lộ trình phù hợp trên BeaconVie.", eyebrow:"CEFR A1–C1", heading:"Biết mình đang ở đâu trước khi bắt đầu học", intro:"Xem nhanh cách CEFR phân chia khả năng và thử một câu mẫu trước khi làm bài đánh giá đầy đủ.", outcomes:["A1–A2: giao tiếp quen thuộc","B1–B2: sử dụng độc lập hơn","C1: xử lý nội dung phức tạp"], appPath:"/placement", lesson:{title:"Câu thử nhanh",explanation:"Chọn dạng đúng để hoàn thành câu. Đây chỉ là một câu preview, không thay thế bài kiểm tra trình độ đầy đủ.",examples:["She ___ English every day.","A. study","B. studies"],practice:"Bạn chọn A hay B?",answer:"B. studies — chủ ngữ ngôi thứ ba số ít ở hiện tại đơn dùng động từ thêm -s/-es."}},
  { slug:"hoc-tu-vung-tieng-anh", title:"Học từ vựng tiếng Anh theo trình độ", description:"Học từ vựng tiếng Anh theo chủ đề và trình độ, ôn tập có hệ thống và đưa từ mới vào luyện tập thực tế.", eyebrow:"Từ vựng", heading:"Học từ vựng để dùng được, không chỉ để nhớ", intro:"Học một từ cùng nghĩa, ngữ cảnh và một câu do chính bạn tạo ra.", outcomes:["Từ theo chủ đề và CEFR","Ví dụ trong ngữ cảnh","Ôn lại bằng recall"], appPath:"/vocabulary", lesson:{title:"Từ mẫu: routine",explanation:"routine /ruːˈtiːn/ (noun): thói quen hoặc chuỗi hoạt động thường xuyên.",examples:["My morning routine starts at 6 a.m.","Reading is part of my daily routine.","Useful pair: daily routine"],practice:"Hoàn thành: Exercise is part of my daily ___.",answer:"routine"}},
  { slug:"ngu-phap-tieng-anh", title:"Ngữ pháp tiếng Anh từ cơ bản đến nâng cao", description:"Học ngữ pháp tiếng Anh theo lộ trình rõ ràng, từ nền tảng đến ứng dụng trong đọc, viết, nghe và nói.", eyebrow:"Ngữ pháp", heading:"Hiểu ngữ pháp để sử dụng tiếng Anh tự nhiên hơn", intro:"Bắt đầu bằng quy tắc ngắn, ví dụ rõ và một câu tự kiểm tra.", outcomes:["Chủ điểm theo trình độ","Ví dụ dễ đối chiếu","Ứng dụng vào câu thật"], appPath:"/grammar", lesson:{title:"Mini lesson: Present Simple",explanation:"Dùng hiện tại đơn cho thói quen, sự thật và hành động lặp lại. Với he/she/it, động từ thường thêm -s/-es.",examples:["I study after work.","She studies every evening.","Do you practise every day?"],practice:"Điền dạng đúng: He ___ (watch) English videos at night.",answer:"watches"}},
  { slug:"luyen-nghe-tieng-anh", title:"Luyện nghe tiếng Anh theo trình độ", description:"Luyện nghe tiếng Anh từ cơ bản đến nâng cao với nội dung phù hợp trình độ và lộ trình học trên BeaconVie.", eyebrow:"Listening", heading:"Luyện nghe vừa sức rồi tăng độ khó từng bước", intro:"Luyện nghe hiệu quả bắt đầu từ dự đoán nội dung, bắt ý chính rồi mới nghe chi tiết.", outcomes:["Nghe theo CEFR","Tập bắt từ khóa","Nghe lại có mục tiêu"], appPath:"/listening", lesson:{title:"Mini listening strategy",explanation:"Trước khi nghe, đoán 3–5 từ có thể xuất hiện. Lượt đầu chỉ tìm ý chính; lượt sau mới tập trung vào chi tiết.",examples:["Topic: ordering coffee","Predict: coffee, milk, size, please","Main idea first → details second"],practice:"Nếu chủ đề là airport, hãy nghĩ 3 từ tiếng Anh bạn có thể nghe thấy.",answer:"Ví dụ: flight, gate, passport."}},
  { slug:"luyen-noi-tieng-anh", title:"Luyện nói tiếng Anh và phản xạ giao tiếp", description:"Luyện nói tiếng Anh, phát triển phản xạ và sự tự tin qua các hoạt động giao tiếp phù hợp trình độ.", eyebrow:"Speaking", heading:"Biến kiến thức thành phản xạ nói tiếng Anh", intro:"Guest có thể thử prompt nói ngắn ngay trên trang; AI feedback và lịch sử luyện tập dành cho tài khoản.", outcomes:["Prompt giao tiếp ngắn","Tập nói thành tiếng","Mở rộng câu từng bước"], appPath:"/speaking", lesson:{title:"Speaking prompt: giới thiệu bản thân",explanation:"Nói thành tiếng 3 câu, không cần hoàn hảo. Ưu tiên nói trọn ý trước rồi mới sửa lỗi.",examples:["My name is ...","I live in ...","I am learning English because ..."],practice:"Nói 3 câu trên mà không đọc lại lần thứ hai.",answer:"Không có một đáp án duy nhất. Mục tiêu là nói đủ 3 ý rõ ràng."}},
  { slug:"luyen-doc-tieng-anh", title:"Luyện đọc tiếng Anh theo trình độ", description:"Luyện đọc tiếng Anh với nội dung phù hợp CEFR, phát triển từ vựng, khả năng hiểu ý và đọc chi tiết.", eyebrow:"Reading", heading:"Đọc đúng trình độ để hiểu nhiều hơn mỗi ngày", intro:"Thử một đoạn ngắn và tìm ý chính trước khi tra từng từ.", outcomes:["Bài đọc vừa sức","Tìm main idea","Học từ trong ngữ cảnh"], appPath:"/reading", lesson:{title:"Mini reading",explanation:"Mai studies English for twenty minutes every morning. She reads a short story and writes down two new words. On weekends, she reviews the words with her sister.",examples:["Who? Mai","When? every morning","Weekend action? reviews words"],practice:"What does Mai do on weekends?",answer:"She reviews the new words with her sister."}},
  { slug:"luyen-viet-tieng-anh", title:"Luyện viết tiếng Anh từ câu đến bài hoàn chỉnh", description:"Luyện viết tiếng Anh theo từng bước, củng cố ngữ pháp, từ vựng và khả năng diễn đạt rõ ràng.", eyebrow:"Writing", heading:"Luyện viết từng bước để diễn đạt rõ ràng hơn", intro:"Bắt đầu bằng một câu rõ ý, sau đó thêm lý do hoặc ví dụ thay vì cố viết dài ngay.", outcomes:["Viết câu rõ nghĩa","Mở rộng bằng because","Tự kiểm tra chủ ngữ và động từ"], appPath:"/writing", lesson:{title:"Mini writing: mở rộng một câu",explanation:"Công thức đơn giản: ý chính + because + lý do. Sau đó kiểm tra chủ ngữ, động từ và dấu câu.",examples:["I learn English.","I learn English because I want to travel.","I practise every day because consistency matters."],practice:"Mở rộng câu: I study English because ...",answer:"Ví dụ: I study English because I want to communicate confidently at work."}},
].map((page) => ({
 ...page,
 guide: [
  `Bắt đầu với phần kiến thức mẫu của ${page.eyebrow} và tự làm bài trước khi xem gợi ý.`,
  "Nếu làm chưa chắc, đọc lại ví dụ và tạo thêm một câu của riêng bạn thay vì chỉ ghi nhớ đáp án.",
  "Sau 5–10 phút, chuyển sang một kỹ năng liên quan để dùng lại kiến thức trong ngữ cảnh khác."
 ],
 faqs: [
  { q: `Tôi có thể học ${page.eyebrow.toLowerCase()} miễn phí trên BeaconVie không?`, a: "Có. Phần hướng dẫn, ví dụ và bài học thử trên trang này mở cho khách. Tài khoản chỉ cần khi bạn muốn lưu tiến độ và học theo lộ trình cá nhân." },
  { q: "Tôi nên bắt đầu ở trình độ nào?", a: "Nếu chưa chắc trình độ, hãy dùng phần kiểm tra CEFR trước. Kết quả giúp bạn tránh học nội dung quá dễ hoặc quá khó." },
  { q: "Học bao lâu mỗi ngày là hợp lý?", a: "Một nhịp 15–25 phút đều đặn thường dễ duy trì hơn học dồn. Quan trọng là có ôn lại và dùng kiến thức vừa học." }
 ]
}));
export const seoPageBySlug = new Map(seoPages.map((page) => [page.slug, page]));
