import type {Metadata} from "next";
import Link from "next/link";
import ResourceLibrary from "@/src/Components/Resources/ResourceLibrary";
import {resources} from "@/src/resources/catalog";
import {siteUrl} from "@/src/seo/public-pages";

export const metadata:Metadata={title:"Kho tài liệu học tiếng Anh miễn phí theo CEFR | BeaconVie",description:"Kho tài liệu tiếng Anh cho người Việt: lọc theo CEFR, kỹ năng và mục tiêu; đọc hướng dẫn, bài học và nguồn uy tín được BeaconVie tuyển chọn.",alternates:{canonical:`${siteUrl}/tai-lieu-tieng-anh`},openGraph:{title:"Kho tài liệu tiếng Anh cho người Việt | BeaconVie",description:"Tài liệu tiếng Anh theo CEFR, kỹ năng và mục tiêu học.",url:`${siteUrl}/tai-lieu-tieng-anh`,siteName:"BeaconVie",locale:"vi_VN",type:"website"}};

export default function Page(){
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage",name:"Kho tài liệu tiếng Anh BeaconVie",url:`${siteUrl}/tai-lieu-tieng-anh`,inLanguage:"vi-VN",description:metadata.description},{"@type":"ItemList",itemListElement:resources.map((r,i)=>({"@type":"ListItem",position:i+1,name:r.title,url:`${siteUrl}/tai-lieu-tieng-anh/${r.slug}`}))}]};
 return <main className="min-h-screen bg-[var(--background)] text-[var(--BeaconVie-ink)]"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="sticky top-0 z-30 border-b border-[var(--BeaconVie-border)] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="text-xl font-black text-[var(--BeaconVie-primary)]">BeaconVie</Link><nav className="hidden gap-6 text-sm font-bold md:flex"><Link href="/hoc-tieng-anh">Lộ trình</Link><Link href="/luyen-nghe-tieng-anh">Kỹ năng</Link><span className="text-[var(--BeaconVie-primary)]">Tài liệu</span></nav><Link href="/login?redirect=%2Ftai-lieu-tieng-anh" className="BeaconVie-button-primary">Đăng nhập</Link></div></header><ResourceLibrary/><footer className="mx-auto max-w-7xl px-5 py-10 text-sm text-[var(--BeaconVie-muted)]">BeaconVie tuyển chọn và biên tập metadata, hướng dẫn học; nội dung của nguồn bên ngoài thuộc đơn vị xuất bản tương ứng.</footer></main>
}