export type Resource = {
  slug: string; title: string; description: string; level: "A1"|"A2"|"B1"|"B2"|"C1"; skill: string; topic: string;
  minutes: number; sourceName: string; sourceUrl: string; featured?: boolean; keywords: string[];
  takeaways: string[]; preview: string[];
};

export const resources: Resource[] = [
  {slug:"cach-hoc-tu-vung-khong-quen",title:"Cách học từ vựng mà không quên sau vài ngày",description:"Chiến lược recall, ngữ cảnh và lịch ôn giúp người học Việt ghi nhớ từ vựng bền hơn.",level:"A2",skill:"Từ vựng",topic:"Phương pháp học",minutes:6,sourceName:"BeaconVie",sourceUrl:"/vocabulary",featured:true,keywords:["học từ vựng tiếng Anh","spaced repetition","recall"],takeaways:["Học từ trong câu thay vì danh sách rời","Tự tạo câu gắn với cuộc sống","Ôn lại theo nhịp 1–3–7 ngày"],preview:["Chọn 5–8 từ cùng một chủ đề và đọc chúng trong câu thật.","Đóng phần nghĩa rồi tự gọi lại từ trong trí nhớ trước khi xem đáp án."]},
  {slug:"luyen-nghe-a2-voi-hoi-thoai-ngan",title:"Luyện nghe A2 bằng hội thoại ngắn: nghe ý chính trước",description:"Quy trình nghe hai lượt dành cho A2, tập trung vào dự đoán, ý chính và từ khóa.",level:"A2",skill:"Nghe",topic:"Giao tiếp",minutes:7,sourceName:"ELLLO",sourceUrl:"https://elllo.org/",featured:true,keywords:["luyện nghe tiếng Anh A2","hội thoại tiếng Anh"],takeaways:["Dự đoán từ khóa trước khi nghe","Lượt một chỉ bắt ý chính","Lượt hai kiểm tra chi tiết"],preview:["Trước khi bấm nghe, nhìn chủ đề và đoán 3–5 từ có thể xuất hiện.","Không dừng ở từng từ lạ trong lượt nghe đầu tiên."]},
  {slug:"present-simple-cho-nguoi-moi-hoc",title:"Present Simple: hiểu nhanh để dùng trong giao tiếp",description:"Hiện tại đơn qua thói quen hằng ngày, lỗi ngôi thứ ba và câu hỏi thường gặp.",level:"A1",skill:"Ngữ pháp",topic:"Nền tảng",minutes:5,sourceName:"British Council LearnEnglish",sourceUrl:"https://learnenglish.britishcouncil.org/free-resources",featured:true,keywords:["thì hiện tại đơn","present simple"],takeaways:["Nhận biết ngữ cảnh dùng hiện tại đơn","Nhớ -s/-es với he/she/it","Tạo câu hỏi với do/does"],preview:["Dùng hiện tại đơn cho thói quen, sự thật và hành động lặp lại.","Với he, she, it, động từ thường thêm -s hoặc -es."]},
  {slug:"phrasal-verbs-b1-theo-ngu-canh",title:"Phrasal verbs B1: học theo ngữ cảnh thay vì học thuộc",description:"Cách nhóm phrasal verbs theo tình huống để dễ nhớ và dùng đúng hơn.",level:"B1",skill:"Từ vựng",topic:"Giao tiếp",minutes:8,sourceName:"Cambridge English",sourceUrl:"https://www.cambridgeenglish.org/learning-english/activities-for-learners/",keywords:["phrasal verbs B1","từ vựng giao tiếp"],takeaways:["Nhóm theo tình huống","Ghi cả câu mẫu","Tự thay chủ ngữ và ngữ cảnh"],preview:["Một phrasal verb dễ nhớ hơn khi đi cùng tình huống cụ thể.","Sau mỗi ví dụ, hãy viết lại câu với một chi tiết thuộc cuộc sống của bạn."]},
  {slug:"doc-tieng-anh-b1-tim-main-idea",title:"Đọc B1: tìm main idea trước khi tra từ",description:"Kỹ thuật đọc nhanh đoạn văn B1 mà không bị mắc kẹt ở từng từ mới.",level:"B1",skill:"Đọc",topic:"Kỹ năng học",minutes:6,sourceName:"BeaconVie",sourceUrl:"/reading",keywords:["luyện đọc tiếng Anh B1","main idea"],takeaways:["Đọc tiêu đề và câu đầu","Đánh dấu từ lặp lại","Chỉ tra từ ảnh hưởng ý chính"],preview:["Mục tiêu lượt đọc đầu không phải hiểu 100% từ vựng.","Hãy trả lời: đoạn này nói chủ yếu về ai, việc gì và vì sao?"]},
  {slug:"viet-cau-b1-voi-because",title:"Viết câu B1 rõ ý với because và ví dụ",description:"Từ một câu đơn, mở rộng thành ý hoàn chỉnh bằng lý do và ví dụ cụ thể.",level:"B1",skill:"Viết",topic:"Kỹ năng học",minutes:7,sourceName:"BeaconVie",sourceUrl:"/writing",keywords:["luyện viết tiếng Anh B1","because"],takeaways:["Viết ý chính trước","Thêm because + lý do","Kiểm tra chủ ngữ và động từ"],preview:["Đừng cố viết dài ngay từ đầu. Hãy đảm bảo câu đầu tiên rõ nghĩa.","Sau đó thêm một lý do cụ thể bằng because."]},
  {slug:"speaking-a2-gioi-thieu-ban-than",title:"Speaking A2: giới thiệu bản thân tự nhiên hơn",description:"Khung nói ngắn giúp người học A2 vượt qua cảm giác bí từ khi giới thiệu bản thân.",level:"A2",skill:"Nói",topic:"Giao tiếp",minutes:5,sourceName:"USA Learns",sourceUrl:"https://www.usalearns.org/",keywords:["luyện nói tiếng Anh A2","giới thiệu bản thân"],takeaways:["Nói theo 3 ý ngắn","Ưu tiên trọn ý trước độ hoàn hảo","Lặp lại với thông tin mới"],preview:["Bắt đầu bằng tên, nơi sống và lý do bạn học tiếng Anh.","Nói thành tiếng một lượt mà không dừng để sửa từng lỗi nhỏ."]},
  {slug:"lo-trinh-b2-tu-hoc-20-phut",title:"Lộ trình B2 tự học 20 phút mỗi ngày",description:"Một nhịp học cân bằng đọc/nghe, vocabulary recall và output cho người học B2.",level:"B2",skill:"Tổng hợp",topic:"Lộ trình",minutes:9,sourceName:"BeaconVie",sourceUrl:"/learning-path",featured:true,keywords:["lộ trình học tiếng Anh B2","tự học tiếng Anh"],takeaways:["8 phút input","5 phút recall","7 phút output"],preview:["Một lịch ngắn nhưng đều có giá trị hơn một buổi học dài rồi bỏ nhiều ngày.","Mỗi phiên nên có cả input và một hành động output nhỏ."]},
];

export const resourceBySlug = new Map(resources.map((item)=>[item.slug,item]));
export const resourceSkills = ["Tất cả", ...Array.from(new Set(resources.map((r)=>r.skill)))];
export const resourceLevels = ["Tất cả","A1","A2","B1","B2","C1"];
