export enum NotificationEventType {
  DAILY_REMINDER = 'DAILY_REMINDER',
  LEARNING_COMPLETED = 'LEARNING_COMPLETED',
  MISSION_COMPLETED = 'MISSION_COMPLETED',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  LEADERBOARD_REWARD_GRANTED = 'LEADERBOARD_REWARD_GRANTED',
  FRIEND_ACTIVITY = 'FRIEND_ACTIVITY',
  CLUB_ACTIVITY = 'CLUB_ACTIVITY',
  COMMUNITY_ACTIVITY = 'COMMUNITY_ACTIVITY',
  AI_FEEDBACK_READY = 'AI_FEEDBACK_READY',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
}

export enum NotificationEventPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
}

export const NOTIFICATION_DOMAIN_EVENT = 'notification.domain';
