import { Injectable } from '@nestjs/common';
import {
  LearningSkill,
  MissionV2Action,
  MissionV2Scope,
  MissionV2Type,
  Prisma,
} from '@prisma/client';
import { PrismaService } from 'src/prisma/prisma.service';

@Injectable()
export class MissionV2TemplateService {
  constructor(private readonly prisma: PrismaService) {}

  async ensureDefaultTemplates() {
    const templates: Prisma.MissionTemplateV2CreateManyInput[] = [
      {
        code: 'V2_DAILY_CURRENT_LESSON',
        title: 'Hoàn thành bài học hôm nay',
        description: 'Hoàn thành bài học tiếp theo trong lộ trình cá nhân hóa.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.PHASE,
        action: MissionV2Action.COMPLETE_LESSON,
        defaultTarget: 1,
        rewardXp: 25,
        rewardCoins: 40,
        priority: 100,
      },
      {
        code: 'V2_DAILY_PRIORITY_SKILL',
        title: 'Luyện kỹ năng ưu tiên',
        description: 'Hoàn thành một hoạt động thuộc kỹ năng AI đang ưu tiên.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.STUDY_LESSON,
        defaultTarget: 1,
        rewardXp: 20,
        rewardCoins: 35,
        priority: 90,
      },
      {
        code: 'V2_DAILY_VOCABULARY',
        title: 'Từ vựng hôm nay',
        description: 'Học số từ mới theo mục tiêu hằng ngày.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.LEARN_WORD,
        defaultTarget: 10,
        rewardXp: 20,
        rewardCoins: 30,
        skill: LearningSkill.VOCABULARY,
        priority: 80,
      },
      {
        code: 'V2_WEEKLY_LESSONS',
        title: 'Tiến bộ trong lộ trình',
        description: 'Hoàn thành các bài học được giao trong tuần.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.LEARNING_PATH,
        action: MissionV2Action.COMPLETE_LESSON,
        defaultTarget: 12,
        rewardXp: 150,
        rewardCoins: 200,
        priority: 100,
      },
      {
        code: 'V2_WEEKLY_SPEAKING',
        title: 'Luyện nói trong tuần',
        description: 'Hoàn thành các bài Speaking được AI đề xuất.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.COMPLETE_SPEAKING,
        defaultTarget: 3,
        rewardXp: 100,
        rewardCoins: 120,
        skill: LearningSkill.SPEAKING,
        priority: 80,
      },
      {
        code: 'V2_WEEKLY_WRITING',
        title: 'Luyện viết trong tuần',
        description: 'Gửi bài viết để AI đánh giá.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.CHECK_WRITING,
        defaultTarget: 2,
        rewardXp: 100,
        rewardCoins: 120,
        skill: LearningSkill.WRITING,
        priority: 80,
      },
      {
        code: 'V2_DAILY_READING',
        title: 'Đọc hiểu hôm nay',
        description: 'Hoàn thành một bài đọc phù hợp với lộ trình của bạn.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.READ_ARTICLE,
        defaultTarget: 1,
        rewardXp: 25,
        rewardCoins: 40,
        skill: LearningSkill.READING,
        priority: 85,
      },
      {
        code: 'V2_WEEKLY_READING',
        title: 'Luyện đọc trong tuần',
        description: 'Hoàn thành các bài đọc được đề xuất trong tuần.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.READ_ARTICLE,
        defaultTarget: 3,
        rewardXp: 100,
        rewardCoins: 120,
        skill: LearningSkill.READING,
        priority: 80,
      },
      {
        code: 'V2_WEEKLY_STUDY_MINUTES',
        title: 'Duy trì thời gian học',
        description: 'Hoàn thành mục tiêu thời gian học trong tuần.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.GLOBAL,
        action: MissionV2Action.STUDY_MINUTES,
        defaultTarget: 60,
        rewardXp: 100,
        rewardCoins: 100,
        priority: 60,
      },
      {
        code: 'V2_DAILY_LISTENING',
        title: 'Luyện nghe hôm nay',
        description:
          'Hoàn thành một bài luyện nghe phù hợp với trình độ của bạn.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.LISTEN_AUDIO,
        defaultTarget: 1,
        rewardXp: 25,
        rewardCoins: 40,
        skill: LearningSkill.LISTENING,
        priority: 85,
      },
      {
        code: 'V2_WEEKLY_LISTENING',
        title: 'Luyện nghe trong tuần',
        description: 'Hoàn thành ba bài luyện nghe trong tuần.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.LISTEN_AUDIO,
        defaultTarget: 3,
        rewardXp: 100,
        rewardCoins: 120,
        skill: LearningSkill.LISTENING,
        priority: 80,
      },
      {
        code: 'V2_DAILY_SPEAKING',
        title: 'Luyện nói hôm nay',
        description: 'Hoàn thành một bài luyện nói và nhận phản hồi từ AI.',
        type: MissionV2Type.DAILY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.COMPLETE_SPEAKING,
        defaultTarget: 1,
        rewardXp: 30,
        rewardCoins: 50,
        skill: LearningSkill.SPEAKING,
        priority: 90,
      },
      {
        code: 'V2_WEEKLY_SPEAKING',
        title: 'Luyện nói trong tuần',
        description: 'Hoàn thành ba bài luyện nói trong tuần.',
        type: MissionV2Type.WEEKLY,
        scope: MissionV2Scope.SKILL,
        action: MissionV2Action.COMPLETE_SPEAKING,
        defaultTarget: 3,
        rewardXp: 120,
        rewardCoins: 150,
        skill: LearningSkill.SPEAKING,
        priority: 85,
      },
    ];

    for (const template of templates) {
      await this.prisma.missionTemplateV2.upsert({
        where: {
          code: template.code,
        },
        create: template,
        update: {
          title: template.title,
          description: template.description,
          type: template.type,
          scope: template.scope,
          action: template.action,
          defaultTarget: template.defaultTarget,
          rewardXp: template.rewardXp,
          rewardCoins: template.rewardCoins,
          rewardFood: template.rewardFood,
          rewardEnergy: template.rewardEnergy,
          rewardHappiness: template.rewardHappiness,
          skill: template.skill,
          priority: template.priority,
          isActive: true,
          metadata: template.metadata,
        },
      });
    }
  }
}
