import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {resourceBySlug,resources} from "@/src/resources/catalog";
import {siteUrl} from "@/src/seo/public-pages";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return resources.map(r=>({slug:r.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const r=resourceBySlug.get(slug);if(!r)return{};const url=`${siteUrl}/tai-lieu-tieng-anh/${r.slug}`;return{title:`${r.title} | BeaconVie`,description:r.description,alternates:{canonical:url},keywords:r.keywords,openGraph:{title:r.title,description:r.description,url,siteName:"BeaconVie",locale:"vi_VN",type:"article"}}}
export default async function ResourceDetail({params}:Props){const {slug}=await params;const r=resourceBySlug.get(slug);if(!r)notFound();const url=`${siteUrl}/tai-lieu-tieng-anh/${r.slug}`;const related=resources.filter(x=>x.slug!==r.slug&&(x.skill===r.skill||x.level===r.level)).slice(0,3);const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:r.title,description:r.description,url,inLanguage:"vi-VN",author:{"@type":"Organization",name:"BeaconVie"},publisher:{"@type":"Organization",name:"BeaconVie",url:siteUrl},keywords:r.keywords.join(", ")},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"BeaconVie",item:siteUrl},{"@type":"ListItem",position:2,name:"Tài liệu tiếng Anh",item:`${siteUrl}/tai-lieu-tieng-anh`},{"@type":"ListItem",position:3,name:r.title,item:url}]}]};
 return <main className="min-h-screen bg-[var(--background)] text-[var(--BeaconVie-ink)]"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><Link href="/" className="text-xl font-black text-[var(--BeaconVie-primary)]">BeaconVie</Link><Link href="/tai-lieu-tieng-anh" className="font-bold">← Kho tài liệu</Link></div></header>
 <article className="mx-auto max-w-5xl px-5 py-10 md:py-16"><nav className="text-sm text-[var(--BeaconVie-muted)]"><Link href="/tai-lieu-tieng-anh">Tài liệu</Link> <span>›</span> {r.skill}</nav><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_280px]"><div><div className="flex flex-wrap gap-2 text-sm font-black text-[var(--BeaconVie-primary)]"><span>{r.level}</span><span>•</span><span>{r.skill}</span><span>•</span><span>{r.minutes} phút đọc</span></div><h1 className="mt-4 text-4xl font-black leading-tight md:text-5xl">{r.title}</h1><p className="mt-5 text-lg leading-8 text-[var(--BeaconVie-muted)]">{r.description}</p>
 <section className="mt-10 rounded-3xl border border-blue-100 bg-blue-50/60 p-6"><h2 className="text-xl font-black">Bạn sẽ học được gì?</h2><ul className="mt-4 space-y-3">{r.takeaways.map(x=><li key={x} className="flex gap-3"><span className="font-black text-blue-600">✓</span><span>{x}</span></li>)}</ul></section>
 <section className="prose prose-slate mt-10 max-w-none"><h2>Đọc thử trước khi đăng nhập</h2>{r.preview.map(p=><p key={p}>{p}</p>)}<p>Hãy áp dụng ngay bằng cách tự tạo một ví dụ hoặc trả lời bằng tiếng Anh trước khi xem thêm hướng dẫn. BeaconVie ưu tiên việc chủ động nhớ lại và sử dụng kiến thức thay vì chỉ đọc.</p></section>
 <section className="mt-10 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-lg"><div className="p-7"><p className="font-black text-blue-600">Phần học đầy đủ trên BeaconVie</p><h2 className="mt-2 text-2xl font-black">Mở bài luyện, lưu tiến độ và nội dung liên quan</h2><p className="mt-3 leading-7 text-[var(--BeaconVie-muted)]">Đăng nhập để tiếp tục phần thực hành, lưu tài liệu vào lộ trình và nhận gợi ý phù hợp với trình độ của bạn.</p><Link href={`/login?redirect=${encodeURIComponent("/tai-lieu-tieng-anh/"+r.slug)}`} className="BeaconVie-button-primary mt-5 inline-flex">Đăng nhập để học tiếp</Link></div></section>
 </div><aside className="space-y-4"><div className="rounded-3xl border bg-white p-5"><p className="text-sm font-bold text-slate-500">Nguồn tham khảo</p><p className="mt-2 font-black">{r.sourceName}</p>{r.sourceUrl.startsWith("http")?<a href={r.sourceUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block text-sm font-black text-blue-700">Mở nguồn chính thức ↗</a>:<Link href={r.sourceUrl} className="mt-4 inline-block text-sm font-black text-blue-700">Học trên BeaconVie →</Link>}</div><div className="rounded-3xl border bg-white p-5"><p className="font-black">Phù hợp với</p><p className="mt-2 text-sm leading-6 text-slate-600">CEFR {r.level} · {r.skill} · {r.topic}</p></div></aside></div>
 {related.length>0&&<section className="mt-16 border-t pt-10"><h2 className="text-2xl font-black">Tài liệu liên quan</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{related.map(x=><Link key={x.slug} href={"/tai-lieu-tieng-anh/"+x.slug} className="rounded-2xl border bg-white p-5"><span className="text-xs font-black text-blue-600">{x.level} · {x.skill}</span><h3 className="mt-2 font-black">{x.title}</h3></Link>)}</div></section>}
 </article></main>}
